language: python
python:
  - 3.7
sudo: false
cache:
  pip: true
  directories:
    - $HOME/.cache/pypoetry

before_install:
  - pip install poetry==0.11.2
  - poetry config settings.virtualenvs.in-project true
  - mkdir -p .venv

install:
- make install
script:
- make test
- codecov
