version: 2.0

jobs:
  build:
    working_directory: ~/tulips
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - restore_cache:
          keys:
            - tulips-{{ .Branch }}-{{ checksum "poetry.lock" }}
            - tulips-
      - run:
          name: Install Python Dependencies
          command: |
            sudo pip install poetry codecov
            make install
      - save_cache:
          key: tulips-{{ .Branch }}-{{ checksum "poetry.lock" }}
          paths:
            - ./.venv
            - ../.cache/pypoetry
      - run:
          name: Run Tests
          command: |
            make test
            codecov
